@url = http://localhost:5249

###
POST {{url}}/slots
Content-Type: application/json

{
    "time": "17/6/2023 00:00:00",
    "doctorName": "budi",
    "cost": 200
}

###
POST {{url}}/slots/query

{
    "doctorName": "budi",
}