@url = http://localhost:5249

###
POST {{url}}/slots
Content-Type: application/json

{
    "time": "21/6/2023 05:30:00",
    "doctorName": "budi",
    "doctorId": "4ceaa21b-c582-429b-a314-cf32275b1f4a",
    "cost": 500
}

###
POST {{url}}/appointments
Content-Type: application/json

{
    "patientName": "Mark",
    "PatientId": "4ceaa21b-c582-429b-a314-cf32275b1f4a",
    "slotId": "7070f61c-62b4-4057-9140-e07880d9b70b"
}

###
POST {{url}}/slots/doctor
Content-Type: application/json

{
    "doctorName": "budi"
}

###
POST {{url}}/slots/getall
Content-Type: application/json
{

}

###
POST {{url}}/slots/getavailable
Content-Type: application/json
{

}

###
POST {{url}}/slots/updatereservation
Content-Type: application/json

{
   "isReserved": false,
   "slotId": "c4e6b69d-31eb-4ebd-be75-909872a9f271" 
}

###
POST {{url}}/appointments/book
Content-Type: application/json

{
   "patientName": "budi",
   "patientId": "c5e6b69d-31eb-4ebd-be75-909872a9f272",
   "slotId": "088795fe-b360-4a47-b600-d66172fddef7"

}

###
POST {{url}}/appointments/iscomplete
Content-Type: application/json

{
   "isCompleted": true,
   "Id": "c5e6b69d-31eb-4ebd-be75-909872a9f272"

}

###
POST {{url}}/appointments/nextappointment
Content-Type: application/json

{
   "doctorName": "budi"
}

###
POST {{url}}/appointments/nextappointments
Content-Type: application/json

{
   "doctorName": "budi"
}

###
POST {{url}}/appointments/cancel
Content-Type: application/json

{
   "appointmentId": "8a6a9608-a820-473d-9893-529b96c6e7cd"
}

###
POST {{url}}/slots/upcoming
Content-Type: application/json

{
   "doctorName": "budi"
}

###
POST {{url}}/slots/upcomings
Content-Type: application/json

{
   "doctorName": "budi"
}

###
POST {{url}}/slots/delete
Content-Type: application/json

{
   "slotid": "088795fe-b360-4a47-b600-d66172fddef7"
}

